### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by akulkarnihawk1995** [siddheshgawde/SpringBootDemo#1]
@siddheshgawde 
**Spring boot project withe following features**

- [ ] Good practices of REST API design for the endpoints
- [ ] Needs an actual database - MySQL preferred
- [ ] Create Student with ID, first name, last name, mobile number (only allowed 10 characters else should give error)
- [ ] Create new Courses table with mappings to Student ID one-to-many relationship
- [ ] Bonus  Task : deploty the API via Docker (Create Dockerfile and upload here)
- [ ] Work on your own branch and create a PR here

**Comment by akulkarnihawk1995** [comment]
@siddheshgawde What's the progress on this ?
